// <auto-generated />
using System;
using Marmilo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Marmilo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MarmiloDbContext))]
    [Migration("20260503202623_AddRedemptions")]
    partial class AddRedemptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Marmilo.Domain.Currency.CurrencyLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_profile_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByParentUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_parent_user_id");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entry_type");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<Guid?>("RewardRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("reward_rule_id");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId");

                    b.HasIndex("CreatedByParentUserId");

                    b.HasIndex("FamilyId");

                    b.HasIndex("RewardRuleId");

                    b.ToTable("currency_ledger", (string)null);
                });

            modelBuilder.Entity("Marmilo.Domain.Families.ChildProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("pet_name");

                    b.Property<int>("PictureId")
                        .HasColumnType("integer")
                        .HasColumnName("picture_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("child_profiles", (string)null);
                });

            modelBuilder.Entity("Marmilo.Domain.Families.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByParentUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_parent_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("families", (string)null);
                });

            modelBuilder.Entity("Marmilo.Domain.Families.FamilyParentMembership", b =>
                {
                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid>("ParentUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.HasKey("FamilyId", "ParentUserId");

                    b.HasIndex("ParentUserId");

                    b.ToTable("family_parents", (string)null);
                });

            modelBuilder.Entity("Marmilo.Domain.GameState.ChildGameState", b =>
                {
                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_profile_id");

                    b.Property<int>("BrushSessionDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("brush_session_duration_minutes");

                    b.Property<int>("CoinsBalance")
                        .HasColumnType("integer")
                        .HasColumnName("coins_balance");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InventoryStateJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("inventory_state_json");

                    b.Property<bool>("Muted")
                        .HasColumnType("boolean")
                        .HasColumnName("muted");

                    b.Property<bool>("PendingReward")
                        .HasColumnType("boolean")
                        .HasColumnName("pending_reward");

                    b.Property<string>("PetStateJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("pet_state_json");

                    b.Property<string>("RoomStateJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("room_state_json");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ChildProfileId");

                    b.ToTable("child_game_states", (string)null);
                });

            modelBuilder.Entity("Marmilo.Domain.Market.MarketItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("item_type");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("market_items", (string)null);
                });

            modelBuilder.Entity("Marmilo.Domain.Parents.ParentUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("auth_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("parent_users", (string)null);
                });

            modelBuilder.Entity("Marmilo.Domain.Redemptions.Redemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChildProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_profile_id");

                    b.Property<int>("Cost")
                        .HasColumnType("integer")
                        .HasColumnName("cost");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid>("MarketItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_item_id");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedByParentUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_parent_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ChildProfileId");

                    b.HasIndex("FamilyId");

                    b.HasIndex("MarketItemId");

                    b.HasIndex("ResolvedByParentUserId");

                    b.ToTable("redemptions", (string)null);
                });

            modelBuilder.Entity("Marmilo.Domain.Rewards.RewardRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrencyAmount")
                        .HasColumnType("integer")
                        .HasColumnName("currency_amount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("reward_rules", (string)null);
                });

            modelBuilder.Entity("Marmilo.Domain.Currency.CurrencyLedgerEntry", b =>
                {
                    b.HasOne("Marmilo.Domain.Families.ChildProfile", "ChildProfile")
                        .WithMany()
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marmilo.Domain.Parents.ParentUser", "CreatedByParentUser")
                        .WithMany()
                        .HasForeignKey("CreatedByParentUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Marmilo.Domain.Families.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marmilo.Domain.Rewards.RewardRule", "RewardRule")
                        .WithMany()
                        .HasForeignKey("RewardRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChildProfile");

                    b.Navigation("CreatedByParentUser");

                    b.Navigation("Family");

                    b.Navigation("RewardRule");
                });

            modelBuilder.Entity("Marmilo.Domain.Families.ChildProfile", b =>
                {
                    b.HasOne("Marmilo.Domain.Families.Family", "Family")
                        .WithMany("ChildProfiles")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Marmilo.Domain.Families.FamilyParentMembership", b =>
                {
                    b.HasOne("Marmilo.Domain.Families.Family", "Family")
                        .WithMany("ParentMemberships")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marmilo.Domain.Parents.ParentUser", "ParentUser")
                        .WithMany("FamilyMemberships")
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("Marmilo.Domain.GameState.ChildGameState", b =>
                {
                    b.HasOne("Marmilo.Domain.Families.ChildProfile", "ChildProfile")
                        .WithOne("GameState")
                        .HasForeignKey("Marmilo.Domain.GameState.ChildGameState", "ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildProfile");
                });

            modelBuilder.Entity("Marmilo.Domain.Market.MarketItem", b =>
                {
                    b.HasOne("Marmilo.Domain.Families.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Marmilo.Domain.Redemptions.Redemption", b =>
                {
                    b.HasOne("Marmilo.Domain.Families.ChildProfile", "ChildProfile")
                        .WithMany()
                        .HasForeignKey("ChildProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marmilo.Domain.Families.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Marmilo.Domain.Market.MarketItem", "MarketItem")
                        .WithMany()
                        .HasForeignKey("MarketItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Marmilo.Domain.Parents.ParentUser", "ResolvedByParentUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByParentUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChildProfile");

                    b.Navigation("Family");

                    b.Navigation("MarketItem");

                    b.Navigation("ResolvedByParentUser");
                });

            modelBuilder.Entity("Marmilo.Domain.Rewards.RewardRule", b =>
                {
                    b.HasOne("Marmilo.Domain.Families.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Marmilo.Domain.Families.ChildProfile", b =>
                {
                    b.Navigation("GameState")
                        .IsRequired();
                });

            modelBuilder.Entity("Marmilo.Domain.Families.Family", b =>
                {
                    b.Navigation("ChildProfiles");

                    b.Navigation("ParentMemberships");
                });

            modelBuilder.Entity("Marmilo.Domain.Parents.ParentUser", b =>
                {
                    b.Navigation("FamilyMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
